/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <string>
#include <fstream>
#include <stdlib.h>
#include "map.h"

using namespace std;

int main(int argc, char *argv[])
{
    // Check Command Line Arguments
    if (argc != 2)
    {
        cerr << "Usage: " << argv[0] << " sokoban_test_file"
             << "\n";
        return 1;
    }

    // Open sokoban test file
    ifstream sokobanFile(argv[1]);
    if (!sokobanFile)
    {
        cerr << "Error: " << argv[1] << " could not be opened"
             << "\n";
        return 2;
    }

    // if (sokobanFile.is_open())
    // {
    //     while (getline(sokobanFile, line))
    //     {
    //         cout << line << endl;
    //     }
    // }

    Map map(sokobanFile);

    return 0;
}
