/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <stdlib.h>
#include "map.h"

using namespace std;

int main(int argc, char *argv[])
{
    // Check Command Line Arguments
    if (argc != 2)
    {
        cerr << "Usage: " << argv[0] << " sokoban_test_file"
             << "\n";
        return 1;
    }

    // Open sokoban test file
    ifstream sokobanFile(argv[1]);
    if (!sokobanFile)
    {
        cerr << "Error: " << argv[1] << " could not be opened"
             << "\n";
        return 2;
    }

    // Initial State
    Map initialMap(sokobanFile);

    // Stick with simple data structure first
    // Successor State Generator
    vector<Map> states;
    states.push_back(initialMap);

    initialMap.moveIsLegal(0);
    initialMap.moveIsLegal(1);
    initialMap.moveIsLegal(2);
    initialMap.moveIsLegal(3);

    return 0;
}
